### ISSUE TITLE
Crash on clicking "About" in settings

### ISSUE THREAD

**Issue by DPS2004** [jaames/playnote-studio#11] opened 2022-04-23 11:36 UTC
```lua
bad argument #2 to 'format' (number expected, got
 string)
stack traceback:
 [C]: in function 'string.format'
 ?: in method 'getTextFormatted'
 ?: in field 'clickCallback'
 ?: in field 'click'
 ?: in method 'click'
 ?: in method 'clickSelection'
 ?: in function <?:490>
```

Downloaded from [playnote.studio](https://playnote.studio/), credits say i'm running v1.0.1

**Comment by jaames** [comment] 2022-04-23 19:44
ah, thanks! I think that's the same bug as #9

**Comment by jaames** [comment] 2022-04-24 13:32
Found the issue; was caused by trying to format the version string as a number rather than a string. Worked fine for "1.0", but not "1.0.1", oops!

Will be fixed in 1.1 :)

**Comment by DPS2004** [comment] 2022-04-24 16:32
but will it break again in 1.1.1 ;)

**Comment by jaames** [comment] 2022-04-24 17:24
one would hope not!! https://github.com/jaames/playnote-studio/commit/2fb55a0867833cf91834093edcd39403834cbc57

**Closed** 2022-04-25 22:02 UTC
